### PR TITLE
Remove unused class, update gradle 4.6, update kotlin 1.2.40, add mvp test

### PR DESCRIPTION
**Pull request by radityagumay**
[Task] Remove unused class, update gradle 4.6, update kotlin 1.2.40, add mvp test

### CODE REVIEW

**Comment by radityagumay** [comment]
@raniejade i just forgot something. this project is android scope. and better we provide an android sample with common design pattern. so, people can understand how using it.

**Review by raniejade — CHANGES_REQUESTED** [review]
As a I mentioned, no fancy MVP thingy - I doubt everyone uses that. A simple spec will do. Also, please don't remove the `non-android-lib`, it's there for a reason.

**Comment by radityagumay** [comment]
@raniejade ok then

**Comment by raniejade** [comment]
@radityagumay there is no need to create a separate PR, just update this one.

**Pull request closed without merging**
