### PR TITLE
[Task] Remove unused class, update gradle version, add jacoco code coverage report, add mvp test

### PR DESCRIPTION
**Pull request by radityagumay**
As many people confuse how to using spek. Here working project with latest Android Studio 3.1.1, kotlin 1.2.31, gradle 4.6.

Sample for working jacoco code coverage, will added merge report with instrument test later.

screen shot 2018-04-19 at 1 04 30 pm
screen shot 2018-04-19 at 1 04 37 pm

@raniejade @hhariri

### CODE REVIEW

**Review by raniejade — CHANGES_REQUESTED** [review]
Wow, thanks for doing this!I would really like to keep the example simple, so just the barebones setup that developers can easily customize. I think this can be split up into several PRs:

- Upgrade to Gradle 4.6, kotlin to latest version, latest android build tools.
- Code coverage

No fancy MVP thingy, just a simple example of using Spek.

**Comment by radityagumay** [comment]
@raniejade great!, will do that. Thanks!

**Comment by radityagumay** [comment]
@rani

**Comment by radityagumay** [comment]
@raniejade i just forgot something. this project is android scope. and better we provide an android sample with common design pattern. so, people can understand how using it.

**Pull request closed without merging**
